zeromq/cppzmq

zmq.hpp
The issue was discovered by clang:
zmq.hpp:504:34: runtime error: load of misaligned address 0x2b38beb224b2
for type 'int32_t' (aka 'int'), which requires 4 byte alignment
I modified the loads of both event and value to be consistent.
=> Fix a misaligned load

zmq.hpp
This lets you create functions that return message_t's by value, and
pass them to send() with no copy.
=> Add an rvalue overload for socket_t::send

zmq.hpp
Fixes this error when building against libzmq3:
zmq.hpp:421:18: error: 'ZMQ_STREAM' was not declared in this scope
stream = ZMQ_STREAM
^
=> Fix backward compatibility

zmq.hpp
Now compiles without error with a pre-C++11 compiler (g++-3.3).
Fixes #53
=> Extend C++11 guard to cover remaining use of std::vector data().

zmq.hpp
MSVC complains about conversion of size_t to int.  The size_t typedef is
defined as an unsigned __int64 on Win64, which triggers the warning. Two
such instances were fixed with static_cast\<int\>(size_t)
=> fixed type mismatch warnings (size_t to int)

zmq.hpp
The issue is sort o the same as here: https://github.com/zeromq/cppzmq/issues/47
Assertion error, when destroing ctx while creating a socket from a different thread: ./src/mutex.hpp:123
Test program:
clang++ -std=c++1y -stdlib=libc++ test.cc libzmq/src/.libs/libzmq.a -I cppzmq -I libzmq/include -o unfixed  && ./unfixed
Tested with 4-1 HEAD
#include <thread>
#include <iostream>
#include <memory>
#include "zmq.hpp"
int main() {
for (int i=0; i< 100000; i++) {
if (i%10==0)
std::cout << "iteration " << i << std::endl;
auto ctx = std::make_shared<zmq::context_t>();
std::thread contextcloser([ctx] {
ctx->close();
});
std::thread socketopener([ctx] {
zmq::socket_t s(*ctx, ZMQ_DEALER);
});
socketopener.join();
contextcloser.join();
}
}
=> Fixes assertion error: src/mutex.hpp:123

zmq.hpp
The zmq_recvmsg() function has been replaced by zmq_msg_recv() since version 3.2.0, and has since been marked as deprecated.
See: https://raw.githubusercontent.com/zeromq/zeromq3-x/master/NEWS
Replace uses of the old function (which was in monitor_t::monitor()) with the more modern function call. Support backwards compatibility with a #DEFINE macro for versions of zmq preceeding 3.2.0
=> Avoid using deprecated function zmq_recvmsg

zmq.hpp
The zmq_msg_recv() function takes its parameters in the order of message, socket, and flags while the zmq_recvmsg() function takes the socket, message, and flags. This commit addresses that difference.
=> Fix usage of zmq_msg_recv and zmq_recvmsg

zmq.hpp
Make the `socket_t::getsockopt()` functions (which wrap `zmq_getsockopt()` ) `const` because they should only access and not modify socket state.
=> Make getsockopt() functions const

zmq.hpp
Fix the following two problems in message_t's range constructor: (1) The range constructor passed the wrong size for iterator-types larger than one byte, (2) The range constructor didn't compile for const-iterators.
=> Fix two issues in message_t's range constructor

zmq.hpp
A better/nicer solution to fix the type mismatch warnings (size_t to int). Working with size_t as long as possible and doing the static_cast right before calling the zmq_poll() function of libzmq
=> Correction to pull request #56

zmq.hpp
When making a debug build with msvc, the range constructor of message_t caused warning 4996: 'std::_Copy_impl': Function call with parameters that may be unsafe. It is actually safe to do what's done in the constructor, so the workaround is to mimic what std::copy does, whitout the range check.
=> Fix warning 4996 in msvc debug build

zmq.hpp
New fill constructor: message_t(const void *data, size_t size). Constructs a new message of the given size and copies the data to the message body. In addition a new rebuild() function that does the same for an already constructed object
=> New fill constructor for message_t

zmq.hpp
Zeromq 3.2.5 exports zmq_ctx_destroy and not zmq_ctx_shutdown.
=> Updating zmq_ctx_shutdown to zmq_ctx_destroy which is imported in zmq.h

zmq.hpp, zmq_addon.hpp
This class handles multipart messaging. It is the C++ equivalent of zmsg.h, which is part of CZMQ (the high-level C binding). Furthermore, it is a major improvement compared to zmsg.hpp, which is part of the examples in the ØMQ Guide. Unnecessary copying is avoided by using move semantics to efficiently add/remove parts.
=> Class for multipart messaging

zmq.hpp
Assertion in destructor of _context_t_ doesn't fail if _close_ method has already been called.
=> Failing assertion in dtor of context_t

zmq_addon.hpp
This allows overloading things such as `ZMQ_DONTWAIT`.  Note that we explicitly mask out `ZMQ_SENDMORE` as it would make no sense to accept that in as one of the flags to `send()`.
=> Enable passing flags in to `send()` and `recv()`

zmq_addon.hpp
Add comments to all functions. Optimize move constructor and move assigment operator, remove size check inside pop/remove/peek. Static assert in pushtyp/addtyp/poptyp in order to avoid pitfall with std::string (pushstr/addstr/popstr should be used for that). Add sanity check for poptyp, size of message must match desired type.
=> Add comments, optimize some functions, add static asserts

zmq_addon.hpp
=> Constructor for std::exception does not take string argument.

zmq.hpp
Added compiler directives to support C++11 in Visual Studio 2015,  since it supports all features used but hasn't updated __cplusplus definition.  Also change out deprecated use of throw() in error_t definition in case of C++11.
=> Visual Studio 2015 definitions

zmq.hpp
- Add a missing underscore.
- Remove const as msg is passed by reference.
Solves #91.
=> Fix message_t::gets.

zmq_addon.hpp
lack of `#include <stdexcept>` in function poptyp when call `throw runtime_error`
=> lack of head file

zmq.hpp
change `zmq_send`  to `zmq_send_const`  for reduce copy in `size_t send (const void *, size_t, int)`
=> reduce copy when send mem block

zmq.hpp
This PR fixes the annoying "conversion from X to Y : possible data loss" warning in MSVC.
=> Fixed warnings in c++11 poll functions

zmq.hpp
It's a misuse of `zmq_send_const`. In function `inline size_t send (const void *buf_, size_t len_, int flags_ = 0)`
This lead to many mistake.
the `zmq_send_const` should be used to send a const mem block, but we may send a std::string which alloc in the stack space. like `sock.send(str.data(), str.size())`. So it's not right to use zmq_send_const here.
I'm sorry for pull it last week.
=> misuse of zmq_send_const

zmq_addon.hpp
if we include target code in c++11 with `-Wall -DNDEBUG`, there are some warning, unused-but-set-variable
=> fix warning unused but set variable

zmq.hpp
See [libzmq new feature](https://github.com/zeromq/libzmq/issues/2227).
The statements are wrapped in DRAFT section because the events are not stable yet.
=> Added new monitor event since libzmq new feature

.gitignore, CMakeLists.txt, cppzmqConfig.cmake.in, zmq.hpp
This PR adds cmake files for installing cppzmq (and be able to find it via `find_package(cppzmq)`).
I've added version number in `zmq.hpp` and set it to `1.0.0` since there doesn't seem to be any tag / version number yet, and I don't know what the version policy should be.
=> Cmake files

zmq.hpp
libzmq 4.2.0 has introduced new poller API.
New introduced here zmq::poller_t class is a wrapper that allows registering callback function. 
example:
```
zmq::poller_t poller;
std::function<void(void)> lambda = []() {
std::cout << "socket ready!!" << std::endl;
};
poller.add(server, ZMQ_POLLIN, lambda)
poller.wait(std::chrono::milliseconds(1000));
```
=> poller_t class based on new libzmq poller API

zmq.hpp
This PR fixes issue submitted #113 to support the legacy stable release tree 4.0.x where zmq_msg_gets() in not available.
=> update directive for ZMQ_MAKE_VERSION check against zmq_msg_gets method

CMakeLists.txt, cppzmqConfig.cmake.in
Export CMake targets to package config via interface libraries. This
allows the user to simple depends on this project and thereby gets
the additionally dependencies like ZeroMQ automatically.
This pull request depends on pull request zeromq/libzmq#2504.
=> cmake: Export targets to package config

zmq.hpp
handler parameter is std::function.
If default-constructed std::function is given to zmq::poller_t::add() as handler parameter it throws an exception in zmq::poller_t::wait() because empty std::function is invoked. This PR checks if handler is empty. If it is, forwards NULL to zmq_poller_add() and does not try to invoke handler on wait().
=> Allow for empty handler parameter in call to zmq::poller_t::add().

zmq_addon.hpp
These methods peeks a part and return a copy of its value as a string or the specified type.
This is practical to observe the message without touching it. I use it to perform various treatments according to meta data the message holds itself.
=> Added peekstr and peektyp methods

zmq.hpp
@bluca As discussed yesterday in the IRC, I found two issues with C++ example (ROUTER/DEALER loosing msgs [1]):
1) `EHOSTUNREACH` was incorrectly handled (something we discussed already). This PR handles this by treating it as other non-terminal errors, like `EAGAIN`.
2) I've realised `send()` with flags `ZMQ_DONTWAIT | ZMQ_SNDMORE` actually ignores `ZMQ_SNDMORE` and sends it **immediately**. This is why the second send in the broker code in the example sent was failing with `EHOSTUNREACH` exception, as was considering 2nd msg as ZID (I guess) and NULL was an unseen as a ZID yet.
For 2); is this the expected behaviour? I would expect this should either ignore `ZMQ_DONTWAIT` or give an `EINVAL` return code. If it's an issue, then it must be a libzmq issue.
Original code of example that …
=> Fix rvalue for socket::send() on EHOSTUNREACH

zmq.hpp
This can cause monitor_t to crash if used with a socket that was
constructed via the move constructor.
Solution: initialise the context pointer variable ctxptr in the move
constructor.
=> Problem: uninitialized context pointer in socket_t move constructor

zmq.hpp
This does not allaw to use monitor_t without a thread.
What is often OK but sometimes not.
Solution:
keep existing interface but add a non blocking alternative.
=> Problem: monitor_t::monitor function is blocking

CMakeLists.txt, cppzmqConfig.cmake.in, libzmqPkgConfigFallback.cmake
Try to find installs of `libzmq` that were performed with autotools with a `pkg-config` fallback. Close #132
@herbrechtsmeier we are trying to add a `pkg-config` fallback for `cppzmq`'s `CMakeLists.txt` to find `libzmq` installs that were done with autotools and thus have no ZeroMQ cmake module around.
Do you have an idea how we can re-introduce the targets you are using for the libs when found via `pkg-config`?
=> CMake: pkg-config Fallback

zmq.hpp
Solution: distinguish cases for libzmq 4.2.0, 4.2.1/4.2.2 and 4.2.3
=> Problem: inconsistency with DRAFT APIs in libzmq 4.2.x

zmq.hpp
There are two overloads of `poll` - one that has `-1` as the default value for the timeout, and one that does not have the timeout argument (which calls the previous one with -1 for the timeout). This makes it ambiguous for the compiler when `poll` is called without the timeout.
This patch removes the second overload as it is not needed since the first one already covers the same case.
=> Removing ambiguous overload of poll

libzmqPkgConfigFallback.cmake
tested on macOS.
for MinGW, just add the corresponding file name but not tested.
=> fix libzmqPkgConfigFallback.cmake for find library in macOS and MinGW

zmq.hpp
Solution: use new on_event_* methods
=> Problem: inconsistent symbol naming for ZMQ_VERSION>=4.2.3

zmq.hpp
When defined ZMQ_BUILD_DRAFT_API=1, you receive an error "'on_event_handshake_succeeded' was not declared in this scope"... which is correct for versions 4.2.1 and 4.2.2.
Function was renamed from 'on_event_handshake_succeed', fixed this by updating the function name.
=> Fix compile error for libzmq 4.2.1 and 4.2.2

zmq.hpp
Reverts zeromq/cppzmq#161
I don't think this change is a good idea. The set of events changed between 4.2.2 and 4.2.3(unreleased). One change involved changing the name of ZMQ_EVENT_HANDSHAKE_SUCCEED to ZMQ_EVENT_HANDSHAKE_SUCCEEDED. The method names in cppzmq on_* correspond to the libzmq events and their names 1-to-1. 
This change removes this 1-to-1 mapping, which is confusing.
cppzmq makes no attempt to map different (DRAFT) API versions of libzmq to a uniform API. While this might appear okay for this identifier, which only contains a typo, a client library of cppzmq must be aware of the exact version of libzmq that is used.
=> Revert "Fix compile error for libzmq 4.2.1 and 4.2.2"

zmq.hpp
Reverts zeromq/cppzmq#162
I am very sorry, I did not read the original PR right. My PR #162 was wrong, #161 was correct. Sorry for that and thanks to @FrankAdesys for taking the time to detail this out.
=> Revert "Revert "Fix compile error for libzmq 4.2.1 and 4.2.2""

CMakeLists.txt, libzmq-pkg-config/FindZeroMQ.cmake
and add it to CMAKE_MODULE_PATH on failed load
this allows downstream packages that have loaded cppzmq to call find_package(ZeroMQ) and succeed without shipping their own copy of the fallback.
Additionally, a check for if the libzmq target is defined avoids duplicate definitions when called multiple times, or if multiple packages have the same shim.
=> call pkg-config fallback FindZeroMQ.cmake

CMakeLists.txt, cppzmqConfig.cmake.in
- remove duplicate top-level install
- copy fallback code to cppzmqConfig.cmake.in
closes #176
=> fix updated FindZeroMQ

CMakeLists.txt
when cppzmq is not the root folder of cmake (i.e., it is embedded in a
super project), CMAKE_SOURCE_DIR will not be the correct path to copy
FindZeroMQ.cmake.
=> fix installation source path of FindZeroMQ.cmake

zmq.hpp, zmq_addon.hpp
Consistently indented some preprocessor directives.
Added a str() method and companion operator<<(std::ostream) similar to multipart_t.
Added some comments to mark the end of preprocessor instructions / class def / namespace def
Added an operator<<(std::ostream) to easily print out multipart_t contents using already defined str() method.
=> std::string conversion for zmq::message_t

zmq.hpp
See individual commits for details.
=> Fix copy/move constructors of poller_t, and make error handling consistent with rest of API

tests/poller.cpp, zmq.hpp
@sigiesec's recent commits with gtests and basics tests for zmq
types (thanks for that!) makes it too convinient to not add some more tests.
* Adding some simple tests for poller_t
* Stripped whitespaces from poller implementation.
=> Problem: poller_t does not have great test coverage

tests/poller.cpp, zmq.hpp
Solution: added tests, added size() method, added add deprecated overload with former signature, changed new add signature to accept handler by value
=> Problem: insufficient tests for poller_t, bad usability since caller of add must store function object

tests/CMakeLists.txt, tests/message.cpp, tests/poller.cpp, zmq.hpp
* Added overload constructor (c++11 only) taking iteratable object.
It would be easier to use std::string, std::array etc to construct
a message now. Making it a draft for now in case it is too greedy
and needs to be more specialize.
* Added equal and not euqal operator to message_t as a recommended
and expected way of comparing objects in C++.
* deprecated C style equal method as operator== should be used instead
(point above).
* Added message_t test covering all available message_t's constructors
and equal, not equal operators.
=> Problem: message_t could be easier to construct and is missing equal not equal operators

tests/message.cpp, zmq.hpp
=> Improved tests and implementation of message_t

appveyor.yml, tests/cmake/googletest.cmake, tests/poller.cpp, zmq.hpp
Windows issues:
* missing includes files
Solution: added missing <memory> and <unordered_map>
Here <map> was replaced with <unordered_map> as there is no need for
sorted map.
* googletest fails because deprecation warning causing errors.
Solution: D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING option added.
* googletest fails because by default, new Visual Studio projects
link the C runtimes dynamically but Google Test links them statically.
Solution: gtest_force_shared_crt=ON option added.
Two last point should fix issue #199.
Besides adding appveyor.yml configuration to add Windows build to
CI in order to prevent accidental Windows build breakage on merge.
For now only Debug configuration as Release requires more time to figure
out.
=> Problem: Windows build broken because of multiple issues

CMakeLists.txt
Will otherwise write `set(PACKAGE_VERSION "4.3.0}")` to `cppzmqConfigVersion.cmake`.
=> Remove unnecessary curly bracket

CMakeLists.txt
Add the ability to explicitly not build tests. Option defaults to ON to keep the current behavior, but give the user the option to disable building of tests.
This option is similair to [`ZMQ_BUILD_TESTS`](https://github.com/zeromq/libzmq/blob/54fd20afdf0a5390b3e1e6a08b1f84f69d4446e4/CMakeLists.txt#L1096-L1100), but just for cppzmq.
=> Problem: tests are always building

tests/poller.cpp, zmq.hpp
On adding invalid socket (e.g. after move) there was exception thrown
but leaving modified and unconsistent internal state.
Besides that there was no possibility to remove a socket that was moved
into.
Solutions: changed internal unordered_map "handlers" to operator on zmq internal pointers and rollback when zmq_poller_add fails.
Added two test cases covering the issues.
=> Problem: poller_t invalid behavior on moved sockets

tests/poller.cpp, zmq.hpp
Issue is reproducible in deprecated add method with empty handler
followed by wait that kicks in (covered by provided unit test).
I would prefer we remove this method completely as maintaining something
that we consider `deprecated` is unnecessary in `draft` API.
=> Problem: poller_t's deprecated add might throw std::bad_function_call

appveyor.yml
Solution: use Appveyor caching for libzmq dependency
@bluca @sigiesec this is from appveyor website:
> Note: By default, saving cache is disabled in Pull Request builds. Use Save build cache in Pull Requests checkbox on the General tab of project settings if you need to save cache during PR builds. This setting is not exposed in YAML to prevent unauthorized cache modifications.
=> Problem: Appveyor build is slow.

appveyor.yml
Solution: add googletest build directory to cache and we get another ~35% speed-up
=> Problem: Appveyor Windows build does not cache googletest

appveyor.yml
Currently appveyor caches whole libzmq directory with all sources and
build artifacts (349MB uncompressed).
Solution: install build artifacts to separate `libzmq` directory and
cache only this (~52.70MB uncompressed).
That way we can save some space on shared cache volume that is 1GB
(compressed data) now.
A build time has decreased  also~5% .
=> Problem: Appveyor caches way too much.

tests/poller.cpp, zmq.hpp
Solution: Added `modify` method based on `zmq_poller_modify` and test cases
covering it.
Reduced code duplication in existing test cases by introducing
`client_server_setup` helper struct.
=>  Problem: poller_t does not support modify

tests/poller.cpp, zmq.hpp
We have a deprecated method `add` in poller that contradicts purpose of a draft
API where it can change without deprecation period.
Solution: remove the method so we do not to maintain it anymore.
=> Problem: deprecated poller's add method in draft API

tests/cmake/googletest.cmake
Building and installing cppzmq brings googletest build artifacts to the
installation destination as well. For example someone building cppzmq
with:
```
cmake -DCMAKE_INSTALL_PREFIX=mydest .
cmake --build --target install
```
gets googletest headers and libraries in `mydest`.
Solution: remove googletest from install target
=> Problem: googletest is also installed into install destination

CMakeLists.txt
When libzmq is installed via a package manager, it causes a CMake warning when building cppzmq, which can be safely ignored.
There's no behavior change with this patch, because when libzmq isn't installed it will still raise a warning ([`find_package(ZeroMQ REQUIRED)`](https://github.com/zeromq/cppzmq/blob/13bf7fdb2c0e0209b24c3fd9980e0ffa68c251b9/CMakeLists.txt#L15) is called a few lines further).
=> Problem: Missing QUIET option causes a CMake warning

tests/poller.cpp, zmq.hpp
It is possible that a user would like to add/remove sockets from
handlers. As handlers and poll items might be removed while not
being processed yet - we have a segfault situation.
Provided unit test `remove_from_handler` demonstrates the problem.
Solution: Modify internal poll item data structure only after processing
of events is finished.
Please note that events processing path performance remains the same when there are
no modification (add/remove) to the poller (no rebuild) - main use case.
As an effect of changes `size` method has been removed as it does not
represent any meaningful information anymore. There are active and pending
(waiting for rebuild) poll items so two different sizes. User can
easily track on their side number of registered sockets if original size
information is …
=> Problem: poller can segfault when modified from registered handler.

CMakeLists.txt
project(cppzmq VERSION ${DETECTED_CPPZMQ_VERSION}) will create a variable called cppzmq_VERSION instead of CPPZMQ_VERSION. This is the case under cmake v3.9.4 .
=> Fix message using empty version variable

tests/poller.cpp, zmq.hpp
Latest poller's fixes in #219 left poller's move constructor and move assignment not updated and invalid.
Solution: In order to prevent this in the future make poller default movable, which results in simpler and safer API. Extra unit tests added to cover missed use cases for move operations.
Additionally bringing back `size` method and added `empty` for completeness - as discussed in #219 . Unit tests updated.
=> Problem: poller move operations not complete

tests/poller.cpp, zmq.hpp
Solution: Add ZMQ_CLIENT and ZMQ_SERVER to socket_type enum.
Update some of draft guarded unit tests to use them.
=> Problem: client/server socket types not defined.

zmq.hpp
Solution: Constructor logic moved to the same place where cleanup is and
marking constructor `default`. Init/cleanup code is in one pleace making
it easier to read/maintain.
=> Problem: poller's constructor is not default generated

.clang-format, demo/main.cpp, tests/active_poller.cpp, tests/context.cpp, tests/main.cpp, tests/message.cpp, tests/multipart.cpp, tests/poller.cpp, tests/socket.cpp, tests/testutil.hpp, zmq.hpp, zmq_addon.hpp
For header only library like cppzmq, whitespace style inherited from
libzmq is too restrictive.
Solution: relaxing whitespace before parens from always to in control
statements only, increased max column width from 80 to 85 and removing
requirement of whitespace after template keyword.
=> Problem: whitespace style too restrictive.

.travis.yml, README.md, ci_build.sh, demo/CMakeLists.txt, tests/CMakeLists.txt
Solution: Enable OSX build for xcode9.1 and clang on Travis.
Besides some more Travis build improvements. Please refer to commits descriptions for more details.
=> Problem: OSX build not enabled in Travis

.travis.yml, ci_build.sh
Solution: libzmq pkg-config build (using autogen) added to Travis CI.
There is an issue with cppzmq where it needs to be installed as well in order to find pkg-config version of libzmq. That will be addressed in separate PR.
=> Problem: libzmq pkg-config build not covered by CI

CMakeLists.txt, README.md, ci_build.sh
Solution: Make sure that FinZeroMQ.cmake is present in cppzmq's build
(binary) directory. That way cppzmq can be used from build/binary directory directly for all the cases.
=> Problem: cppzmq needs to be installed for pkg-config libzmq

.travis.yml, ci_build.sh, tests/CMakeLists.txt
Solution: Enable coveralls for one linux build target and fix coveralls
configuration.
=> Problem: Coverage with coveralls not working

README.md
Solution: Show Linux, OSX and Windows labels on build badges for more
visibility on supported platforms.
Additionally added license badge.
=> Problem: README build badges too generic

cppzmqConfig.cmake.in, tests/monitor.cpp, tests/testutil.hpp
Problem: #209 cppzmq fails with cmake 3.6.3 and above
Solution: remove problematic cmake lines as they seem to be not necessary.
Problem: monitor_t tests not event driven 
Solution: instead of waiting for fixed amount of time for events, react
as soon as events are triggered.
- Total running time of unittest reduced 10x (from ~300ms to 30ms).
- Reduced code duplication by reusing testutil's constructs.
=> Problem: #209 and monitor_t tests not event driven

tests/message.cpp, zmq.hpp
This commit introduces new socket_type enumeration values as well
as the following supporting functions:
socket_t::join()
socket_t::leave()
message_t::group()
message_t::set_group()
=> Add support for RADIO/DISH sockets if draft API is enabled

libzmq-pkg-config/FindZeroMQ.cmake
If libzmq is only available as a shared library and not a static one
then cmake fails with:
-- CMake libzmq package not found, trying again with pkg-config (normal install of zeromq)
-- Found PkgConfig: /home/fabrice/buildroot/output/host/bin/pkg-config (found version "0.28")
CMake Error at CMakeLists.txt:20 (message):
ZeroMQ was not found, neither as a CMake package nor via pkg-config
This is due to the fact that ZeroMQ_FOUND is not set to ON even if
ZEROMQ_LIBRARY is TRUE:
if(ZeroMQ_LIBRARY AND ZeroMQ_STATIC_LIBRARY)
set(ZeroMQ_FOUND ON)
endif()
So change AND by OR as suggested in
https://github.com/zeromq/cppzmq/issues/266
Fix #266
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> fix install without static libzmq

tests/multipart.cpp, zmq_addon.hpp
i'll get the last message in some situations，but have to do like this :
```
multimsg msgs;
auto msg = msgs[msgs.size() - 1];
func(msg.size());
auto *msg = msgs.end() - 1;
```
but, std::queue have some method 'front' and 'back'. so maybe i can simply do this ？ :
```
multimsg msgs;
auto msg = msgs.back();
```
=> add front and back

tests/CMakeLists.txt
Solution: Use Threads cmake module as suggested in this thread:
https://cmake.org/pipermail/cmake/2016-February/062729.html
I was able to reproduce with gcc 8.2.1 and cmake 3.13.2.
=> Problem #284: tests and pthread link error with with gcc

tests/CMakeLists.txt, tests/cmake/catch.cmake
Solution: Added integration with CTest to existing unit test framework
based on Catch. ctest -v returns list of run tests now.
Changes:
* downloading and using Catch cmake modules that `unit_tests
--list-test-names-only` for add_test internally
=> Problem #268: CTest output without tests details

zmq.hpp
Uses zmq_msg_get() to get some integer properties on the message.
Fixes #277.
=> Add message_t::get()

zmq.hpp
- Replaced NULL and 0s used as pointers with ZMQ_NULLPTR (defined as nullptr on C++11, as 0 otherwise)
- Added override to the when() member function
=> Removed warnings when compiling with C++11 enabled

tests/message.cpp
Testing ZMQ_SHARED property only, since other properties (ZMQ_MORE and ZMQ_SRCFD) depend on socket operations.
Following PR #295.
=> Unit tests for message_t::get()

zmq.hpp
Solution: Not needed since the void* can be obtained from the API of context_t.
I also simplified the initialization of socket_t.
=> Problem: Friendship between socket_t and context_t

zmq.hpp
zmq_poll mutates the input array, so have const qualifiers for the poll functions does not make sense.
Solution: Remove const qualifiers and const_cast
=> Problem: poll is mutating by definition

zmq.hpp
Solution: Remove specifiers, since they are implicitly inline
=> Problem: Redundant inline specifiers for member functions

tests/socket.cpp, zmq.hpp
Solution: Add overloads to proxy and proxy_steerable taking socket_t
objects
Additionally deprecate the void* overloads.
=> Problem: proxy is not typesafe

tests/message.cpp, zmq.hpp
Solution: Deprecate old functions and add overloads taking non-const
references
=> Problem: message_t move and copy are mutating but take const

tests/context.cpp, tests/message.cpp, tests/monitor.cpp, tests/poller.cpp, tests/socket.cpp, zmq.hpp, zmq_addon.hpp
Solution: Implement for socket_t, context_t, message_t and poller_t
Additionally remove dependency on `<functional>` by refactoring poller_t
and remove unused `<unordered_map>` include.
=> Problem: Missing swap functions

zmq.hpp
Solution: Change wait_all parameter type to std::chrono::milliseconds
"zmq_poller_wait_all shall wait timeout milliseconds" http://api.zeromq.org/4-3:zmq-poller
=> Problem: zmq_poller_wait_all is called with microseconds count

zmq.hpp
Solution: Use std::copy instead of a raw loop and fix a conversion
warning
=> Problem: Performance of message_t construction can be improved

zmq.hpp
This to avoid the following warning with the '-Wold-style-cast' flag enabled :
./zmq.hpp:763:29: warning: use of old-style cast [-Wold-style-cast]
return (size_t) nbytes;
^
./zmq.hpp: In member function ‘size_t zmq::socket_t::recv(void*, size_t, int)’:
./zmq.hpp:793:29: warning: use of old-style cast [-Wold-style-cast]
return (size_t) nbytes;
=> Use C++ cast instead of old style cast

tests/CMakeLists.txt, tests/socket.cpp, tests/socket_ref.cpp, zmq.hpp, zmq_addon.hpp
Solution: Introduce a socket_ref that is a non-owning nullable reference to a socket
This is a quite big PR with a few small additional types to improve type safety. The API is intentionally minimal, but can be extended at later points. Some design decision:
1. `socket_ref` is a trivially copyable type with the same layout as `void*`, making it a step towards typesafe polling
2. `socket_ref` is provides comparison and hashing, making it suitable for containers like `std::map` or `std::unordered_set`. In addition to being a non-owning reference, makes the use of `void*` obsolete (for C++11).
3. A `handle()` function is provided to get the underlying `void*` (solving https://github.com/zeromq/cppzmq/issues/140), since `native_handle()` implies an operating system native socket handle, the …
=>  Problem: No type-safe alternatives when polling or needing a reference to a socket

.travis.yml, zmq.hpp
Solution: Mark functions noexcept and assert instead of throwing
=> Problem: zmq_msg_init never fails

README.md, tests/CMakeLists.txt, tests/active_poller.cpp, tests/buffer.cpp, tests/poller.cpp, tests/socket.cpp, zmq.hpp, zmq_addon.hpp
Solution: Add functions taking buffers and enum class flags
1. `enum class` flags `send_flags` and `recv_flags` instead of `int`s for safer `send` and `recv`.
2. Result structs `send_result`, `recv_result` and `recv_buffer_result` so that no information returned from libzmq is lost, removing ambiguity on EAGAIN (solving https://github.com/zeromq/cppzmq/issues/84 and https://github.com/zeromq/cppzmq/issues/61).
3. Buffer classes replacing `void*` and `size_t` pairs, based on `boost::asio::buffer` and the [Networking TS](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/n4771.pdf) `std::net::buffer` that will likely get added to C++23. This synchronizes the API of cppzmq with future standard C++ networking API (and current `boost::asio`), making it easier to use (and harder to misuse) …
=> Problem: send/recv functions lack type-safety

tests/active_poller.cpp, tests/poller.cpp, zmq.hpp, zmq_addon.hpp
Solution: Add class enum flags and a new poller_event struct
=> Problem: Type-safety of poller_t and active_poller_t can be improved

zmq.hpp
For some reason that I didn't get to the root cause of, gcc 4.8.1 (that I'm stuck with) does not like the initializer for `unique_ptr` implemented as a lambda:
```
third_party/zmqcpp/repo/zmq.hpp: In constructor 'zmq::poller_t<T>::poller_t() [with T = std::function<void(zmq::event_flags)>]':
third_party/zmqcpp/repo/zmq.hpp:1871:5: error: converting to 'std::unique_ptr<void, zmq::poller_t<std::function<void(zmq::event_flags)> >::destroy_poller_t>' from initializer list would use explicit constructor 'std::unique_ptr<_Ty, _Dx>::unique_ptr(std::unique_ptr<_Ty, _Dx>::pointer) [with _Ty = void; _Dx = zmq::poller_t<std::function<void(zmq::event_flags)> >::destroy_poller_t; std::unique_ptr<_Ty, _Dx>::pointer = void*]'
poller_t() = default;
^
In file included from networking/ipc/ipc.cc:6:0: …
```
=> make poller_t work with ancient gcc 4.8.1

zmq.hpp
the 'Space' ASCII character should also be recognized as such.
=> Fix ASCII character detection in conversion to std::string

.travis.yml, README.md, ci_build.sh, tests/socket_ref.cpp, tests/utilities.cpp, zmq.hpp
Solution: Use intrinsic instead of std::is_trivially_copyable for gcc versions older than 5.
=> Problem: C++11 partially supported on gcc 4.8

zmq.hpp
Solution: Refactoring and addition deprecation of a send function taking
int flags
Warnings were only emitted when using clang.
=> Problem: Warnings about send being deprecated

tests/socket_ref.cpp
Solution: Use memcpy instead of reinterpret_cast
Fixes #346.
=> Problem: Strict aliasing warning in tests

tests/buffer.cpp, zmq.hpp
Solution: A function str_buffer specifically for
creating buffers for null terminated string literals.
Before
```C++
s.send(zmq::buffer(std::string_view{"ping"})); // C++17
auto s = "ping";
s.send(zmq::buffer(s, std::strlen(s))); // C++11
```
After
```C++
s.send(zmq::str_buffer("ping"));
```
=> Problem: Sending string literals is awkward

zmq.hpp
Solution: Some compilers incorrectly define `__GNUC__`, added workaround for clang and icc.
=> Problem: Build error with clang

zmq_addon.hpp
Switch zmq_addon.hpp to include zmq.hpp using "zmq.hpp" instead of <zmq.hpp>  This allows it to look in the current directory for the header file.  This enables the ability to have cppzmq as a subdirectory of an included folder vs needing to have the cppzmq on the include search path, and makes it less likely the wrong version would get included if more than one zmq.hpp header happened to be available.
This is a second PR based on conversation from #355
=> Switch zmq_addon.hpp to include zmq.hpp using "zmq.hpp" instead

zmq.hpp
Solution: add nodiscard attribute to recv functions
=> Problem: recv return value should not be ignored

README.md, tests/CMakeLists.txt, tests/recv_multipart.cpp, tests/send_multipart.cpp, zmq.hpp, zmq_addon.hpp
Solution: Add generic algorithms for sending and receiving multipart
messages.
A possible future extension to these functions is a `recv_multipart_n` where for writing to fixed size containers.
=> Problem: Handling multipart messages is complex

zmq.hpp
Solution: Close context/socket if move assigned to
The problem is the following
```c++
void f(socket_t& a, socket_t& b)
{
a = std::move(b);
}
```
Currently after calling this function `b` will be the socket that used to be `a`, which I think is surprising. After this PR `b` will be an "empty" socket.
Since this is only changing the value of a moved-from objects it should not break user code, unless they are doing something they shouldn't be doing.
=> Problem: Move assigned objects still alive

tests/message.cpp, zmq.hpp
Solution: add to_string() function.
=> Problem: message_t to string is hard

CMakeLists.txt
Solution: Remove architechture checks from cmake version file
Since this is a header only library there is no need to check for 32 vs 64bits.
See similar problem: https://github.com/onqtam/doctest/pull/225
=> Problem: Invalid 32bit issues when using Conan

tests/context.cpp, zmq.hpp
Solution: Add shutdown(). This function is required
for clean termination of the zmq context in multi-threaded
applications where sockets are used in threads. In particular
if blocking operation are used and if sockets can be created
at any time.
=> Problem: shutdown() missing for context_t

tests/active_poller.cpp, tests/buffer.cpp, tests/message.cpp, tests/monitor.cpp, tests/multipart.cpp, tests/poller.cpp, tests/recv_multipart.cpp, tests/send_multipart.cpp, tests/socket.cpp, tests/socket_ref.cpp, tests/utilities.cpp, zmq.hpp, zmq_addon.hpp
We have a .clang-format file but over the past 1.5 years several deviations from the defined formatting have evolved. This reformats all files with clang-format to reestablish consistent formatting.
=> Reformat all files with clang-format

tests/context.cpp, zmq.hpp
Solution: Define an enum class for the context options
I'm not sure what to do about the options that have a value of -1, with this change trying to get them results in an exception with the last set errno.
=> Problem: Context lacks typesafe options

.travis.yml, tests/context.cpp, zmq.hpp
Solution: Guard usage of libzmq macros
Fixes https://github.com/zeromq/cppzmq/issues/385
=> Problem: Macros not defined in older versions 

CMakeLists.txt
Wrapping calls to `find_package` allows building cppzmq without doing `find_package(ZeroMQ)` if the libzmq target is already defined.
This occurs when building a project which vendors all of its dependencies with `add_subdirectory`, resulting in targets being defined and find_package to fail. 
Note: I agree that vendoring dependencies in generally bad practice but this is a requirement in our context as we are building a PyPI wheel.
=> Wraping calls to find_package

zmq_addon.hpp
Solution: remove template type checks if there is only partial C++11 support
=> Problem: send_multipart fails on old gcc versions

tests/CMakeLists.txt, tests/codec_multipart.cpp, tests/multipart.cpp, zmq.hpp, zmq_addon.hpp
Solution: add encode/decode methods to `multipart_t` giving a codec compatible with the CZMQ equivalent.
This is part of what was initially #388.
=> Problem: lack conversion `message_t` and `multipart_t`

tests/socket.cpp, tests/testutil.hpp, zmq.hpp
Solution: Implement a type for each socket option.
Each option has an associated type, therefore they
can't be simply defined as an enum class.
That's a lot of options! I think this is one of the last places that are truly dangerous in the current API, where e.g. `s.setsockopt(ZMQ_ROUTING_ID, std::string("foo"));` will not do what you expect.
=> Problem: Socket options lack type-safety 

zmq.hpp
Solution: Add check to guard against passing null to memcpy
=> Problem: UB in message_t constructor

zmq_addon.hpp
Fixes grammatical error in multipart_t:str() function.
=> Address Grammatical Error in multipart_t:str()

zmq.hpp
This commit fixes a regression introduced in a3e5b54c3 (Problem: Socket
options lack type-safety (#393)).
It addresses the following error reported when building the project
on macOS 10.11.6.
Errors like the following:
```
cppzmq/zmq.hpp:1325:39: error: default initialization of an object of const type 'const affinity_t' (aka 'const integral_option<4, unsigned long long, false>') without a user-provided default constructor
```
Compiler version:
```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Similar issues:
* https://github.com/tensorflow/tensorflow/issues/28839
error: default initialization of an object of const type 'const …
=> Fix error: default initialization of an object of const type

tests/codec_multipart.cpp, zmq_addon.hpp
Solution: Always write message part sizes
using network order.
=> Problem: No endian check in encoding

README.md, tests/buffer.cpp, tests/message.cpp, tests/socket.cpp, zmq.hpp
Solution: Unify string_view feature checks. Document how users are expected to use exported macros and how they can define macros to control behaviour.
=> Problem: Feature checking inconsistencies

tests/context.cpp, zmq.hpp
Solution: add handle() and mark operators as deprecated
=> Problem: implicit conversion operators in context

examples/pubsub_multithread_inproc.cpp
I had a really tough time figuring out how to do simple multi-threaded pub-sub with cppzmq; I finally figured it out so I'd like to add it.
=> Add an example

tests/monitor.cpp, zmq.hpp
Until now, we only assigned the _handle on
`zmq::socket_t::operator=(socket_t&&)`. This manifests when trying to
monitor a socket initialized by that constructor.
To avoid changing the public interface of the socket_t class, we tested
for the specific monitor usecase, since it's the only class accessing
zmq::socke_t::ctxptr.
NOTE: When running the new unit-test without the fix, it might hang on
`zmq_socket_monitor(socket_, NULL, 0)`. We haven't figured out the cause
for that, but we deemed it unimportant (or at least out of scope).
=> Bugfix: socket_t move assignment doesn't initialize ctxptr

tests/active_poller.cpp, tests/testutil.hpp, zmq.hpp, zmq_addon.hpp
Solution: Check if socket already added before storing.
Add requirement that the handler is non-null. Improve
checks for zmq error codes.
=> Problem: Active poller double add mutates handler

zmq.hpp
Solution: Include headers before checking macros and add additional checks for _MSVC_LANG.
Fixes https://github.com/zeromq/cppzmq/issues/426
=> Problem: C++ version not correctly estimated

tests/message.cpp, zmq.hpp
Solution: Constructor taking generic ranges including string literals includes the null terminated char in
the message. Deprecate function and add overloads for strings.
This fixes the root cause of a problem observed in https://github.com/zeromq/cppzmq/issues/396 and discussed here https://github.com/zeromq/cppzmq/pull/397
=> Problem: message_t ctor string inconsistency 

zmq.hpp
Fixes #446 
It turns out that the use of the deprecation macro before this constructor does not play well with vs2015.
This was introduced at the last commit before the release.
=> Fix VS 2015 syntax error with macro

tests/cmake/catch.cmake
Solution: Use a fixed commit instead of a branch
See https://github.com/zeromq/cppzmq/issues/457 and PR build errors. The master branch does not exist any more, and there are incompatible changes on the devel branch.
=> Problem: Changes in Catch2 causes errors

zmq.hpp
Solution: Deprecated it, it is not related to connect/disconnect.
=> Problem: connected() is confusing

zmq_addon.hpp
Solution: Silence them with casts
=> Problem: conversion warnings

zmq.hpp, zmq_addon.hpp
Solution: Use if constexpr where possible in C++17
=> Problem: if constexpr warnings on MSVC

tests/socket.cpp, zmq.hpp
Solution: Make zmq::fd_t available and use in poller_event
This is currently available as zmq::sockopt::cppzmq_fd_t, so this is techincally a breaking change. I could add a typedef there for backward compatibility reasons if requested.
=> Problem: zmq_fd_t not used/available in zmq

zmq.hpp
Close #469
As mentioned in the issue and the referred comment, this PR is in particular needed for the migration to Catch2, which exposed that these operators were not covering some cases (e.g. `socket_ref` vs `socket_t`).
This generalization is based on polymorphism and improves const correctness, without exploiting custom cast operators of `socket_ref` and `socket_t` (indeed, it is not so clear to me the situation of these conversion functions, and their const correctness).
@gummif has for sure insight on this and may want to give a final feedback on this.
=> Generalize arithmetic operators for socket_base and derived

zmq.hpp
The objects _eventMsg_ and _addrMsg_ have the type **zmq_msg_t**.
Since the event handlers might throw, this could have caused a leak of data associated with _eventMsg_.
For _addrMsg_, the constructor of std::string could have thrown ( although this is unlikely ).
This PR replaces raw  **zmq_msg_t** objects with **zmq::message_t** objects in _monitor_t::check_event_.
=> Fix for potential memory leak in monitor_t::check_event

examples/CMakeLists.txt
without this, compilation failed with error `/usr/bin/ld: cannot find -lcppzmq`
=> Fix failed compilation for the examples

zmq.hpp
Resolving issue #462 and then some.
This adds the GATHER, SCATTER, CHANNEL, PEER and DGRAM socket types to `zmq::socket_type`. I can't find *any* documentation about DGRAM but since it was requested and does exist in zmq.h I figured I'd include it. I'm guessing that's when you map ZeroMQ messages to UDP datagrams?
=> Add all draft socket types up to libzmq 4.3.4

tests/multipart.cpp, zmq_addon.hpp
This adds socket_ref support to `multipart_t`'s constructor and `send`/`recv` member functions, resolving issue #448 . All previously took a `socket_t&` instead. I don't *think* this will break anything, but if preferred I can add alias functions for `socket_t&` back in.
=> Add support for socket_ref to multipart_t ctor/send/recv 

zmq.hpp
linked issue #484
Relevant manual pages... 
http://api.zeromq.org/master:zmq-ctx-destroy
http://api.zeromq.org/master:zmq-ctx-term
zmq::context_t::close currently uses zmq_ctx_destroy when it should use zmq_ctx_term
=> context_t close no longer uses deprecated function

.travis.yml
Solution: Use pip3 instead of pip to install coveralls.
=> Problem: cpp-coveralls can no longer be installed using Python2 pip.

zmq.hpp
A rather straightforward fix for allowing access to handshake events in stable libzmq v4.3.0 which they were promoted as stable API.
=> Fix handshake event don't need DRAFT API in libzmq v4.3.0 and above

zmq.hpp
Solution: default to std::chrono::milliseconds
=> Problem: poll default timeout is deprecated

tests/multipart.cpp, zmq_addon.hpp
This adds equality operators to `multipart_t` for convenience.
=> Add == and != operators for multipart_t

zmq.hpp
If you use a compiler outside of _MSC_VER and _GNUC__, then the if-else check doesn't provide a fallback for ZMQ_DEPRECATED macro which leads to a build failure.
Specifically in my case , I am using Oracle's SunPro 5.13.0.
My suggestions is to fallback to noop in case you don't recognize a compiler. Addressed #516
=> ZMQ_DEPRECATED doesn't fallback for unrecognized compiler

README.md
Solution: Add a simple overview of types and functions to begin with
=> Problem: No API documentation or overview

zmq.hpp
cf. https://gcc.gnu.org/projects/cxx-status.html#cxx14
=> Suppress ZMQ_EXTENDED_CONSTEXPR on gcc with partial C++14 support

examples/pubsub_multithread_inproc.cpp
With GCC12, I get this error:
```
../subprojects/cppzmq-4.8.1/examples/pubsub_multithread_inproc.cpp: In function ‘void PublisherThread(zmq::context_t*)’:
../subprojects/cppzmq-4.8.1/examples/pubsub_multithread_inproc.cpp:14:23: error: ‘sleep_for’ is not a member of ‘std::this_thread’
14 |     std::this_thread::sleep_for(std::chrono::milliseconds(20));
```
This is because [sleep_for is part of <thread>](https://en.cppreference.com/w/cpp/thread/sleep_for), which is not included in the example. This PR fixes that.
=> examples: fix missing header

.github/workflows/ci.yml, tests/monitor.cpp
Solution: Do not require delayed connection event
=> Problem: Intermittent monitor test failures

zmq_addon.hpp
Otherwise it creates an error on some environments
=>  Disambiguation from other max functions

zmq.hpp
More convenient, like the constructor `message_t(const std::string &str)`
=> Rebuild with string argument, like the constructor

zmq_addon.hpp
This type of function should not throw, adding noexcept
=> Fixes warning noexcept

zmq.hpp
=> add function for adding file descriptor to poller_t

tests/active_poller.cpp, zmq.hpp, zmq_addon.hpp
Add file descriptor support for zmq::active_poller and zmq::base_poller_t.
Note: On Windows, only socket file descriptors are supported. This is a limitation of libzmq.
=> Add file descriptor support for poller

tests/poller.cpp, zmq.hpp
To avoid allocating (due to std::vector), I would like to use a static array for creating poller events. However, the `wait_all` method currently is hardcoded to accept only vectors. This PR addresses that by making `wait_all` a templated function.
=> allow generic sequence of poller events

tests/CMakeLists.txt, tests/buffer.cpp, tests/codec_multipart.cpp, tests/context.cpp, tests/message.cpp, tests/multipart.cpp, tests/recv_multipart.cpp, tests/send_multipart.cpp, tests/socket.cpp, tests/socket_ref.cpp, tests/testutil.hpp, tests/utilities.cpp
Migrating from Catch2 v2 to v3 to significantly improve compilation times.
=> Update to Catch2 v3

zmq.hpp
Currently `ZMQ_EVENT_MONITOR_STOPPED` directly returns from function without an indicator. With a `on_monitor_stopped` function callback anyone can distinguish stop event from errors and might log this event.
=> Add on_monitor_stopped function for monitor_t

.github/workflows/ci.yml, CMakeLists.txt
This option added ZMQ_BUILD_DRAFT_API to the compile definitions. However, this should be propagated by libzmq (see https://github.com/zeromq/libzmq/pull/4323 and https://github.com/zeromq/cppzmq/issues/477).
Closes https://github.com/zeromq/cppzmq/issues/477.
=> Remove ENABLE_DRAFTS option

README.md
document CPPZMQ_BUILD_TESTS
add git clone step
adjust semantics to be more clear
formatting
=> document CPPZMQ_BUILD_TESTS and adjust formatting and semantics of build instructions

zmq.hpp
I may lack sufficient context for this to be a useful PR, so please feel free to close if this is not welcome.
For no particular reason I saw an analogous PR to another R package repo in my GitHub home page:
https://github.com/marzer/tomlplusplus/pull/263
I searched the main R package repo for other similarly-affected packages, which includes {clustermq}, which bundles this repo as a submodule:
https://github.com/mschubert/clustermq/tree/master/src
Here's the documentation I could find about why this matters:
https://en.cppreference.com/w/cpp/language/user_literal
```c++
// error: all names that begin with underscore followed by uppercase
// letter are reserved (NOTE: a space between "" and _).
double operator"" _Z(long double);
```
=> Remove space in custom string literal

zmq.hpp
=> Fix std::max compilation error on Windows

CMakeLists.txt, tests/CMakeLists.txt, tests/timers.cpp, zmq.hpp
Fixes #575 
This is a draft to add support for the `zmq_timers_*` functions.
Please let me know what are the requirements to get it merged.
=> Add zmq_timers support

tests/message.cpp, zmq.hpp
=> Update zmq::message_t::str with max_size
