- zmq.hpp
- Fixed some const-correctness issues
- C++11-ified some stuff: overloads with C++11 types, nothrow, std::chrono
- Added some template methods to work with messages and sockets
- Added overloads for std::string where const char* parameters are expected
- Added some overloads accepting std::vector or iterators
> Enhanced const-correctness and made interface more C++-ish

- zmq.hpp
Additionally, I've changed some tabs to spaces and removed trailing spaces.
> Create a binding for zmq_msg_gets.

- zmq_addon.hpp
addd ` operator[]` and `at` function for direct access msgs
> addd operator[] and at function for direct access msgs

- zmq_addon.hpp
add iterator for msgs access of mulitpart_t
> add iterator for msgs access of mulitpart_t

- zmq.hpp
error zmq_send_const undefined and zmq_msg_gets undefined
> fix build error with libzmq-3.2.5

- zmq_addon.hpp
fixed peektyp check index
added missing return
> fixed peektyp check and return value

- CMakeLists.txt
- cppzmqConfig.cmake.in
> added QUIET to avoid false cmake warning (missing ZeroMQ)

- zmq.hpp
> Revert "Fix rvalue for socket::send() on EHOSTUNREACH"

- zmq.hpp
fixing #147 by adding new DRAFT API handling.
> Fix #147 issuse

- README.md
Because evidently, I would not get it right on the first try ;)
> Markdowning the README

- zmq.hpp
Solution: Added explicit static_cast
> Problem: implicit type conversion warning

- zmq.hpp
> Reduce the duplication.

- zmq.hpp
Implements request as per #155.
> Added wrapper for context options

- README.md
Simple attempt to resolve #197
> Added include directory to CMake instructions

- tests/poller.cpp
- zmq.hpp
* Converted tabs to to 4 spaces to be consistend with the rest of the
code
* Stripped white spaces from the end of lines
>  Problem: non consistent whitespace formatting

- README.md
Solution: add section on design goals and supported platforms to README, improve overall structure of README
> Problem: design goals and supported platforms are not explicitly stated

- zmq.hpp
Fixes #171, see the discussion there.
> Add retry of zmq_ctx_destroy in context_t::close()

- tests/monitor.cpp
- zmq.hpp
Solution: Implement a move assignment operator for monitor_t
> Problem: monitor_t incorrectly deletes socket_t move assignment operator

- zmq.hpp
Solution: Add macros detecting C++14 and C++17
> Problem: Missing detection of standards greater than C++11

- tests/message.cpp
- zmq.hpp
Solution: Add function and qualify with nodiscard like std types
> Problem: message_t lacks empty() function

- tests/socket.cpp
- zmq.hpp
Solution: Provide a default constructor
> Problem: socket_t can not be default constructed

- tests/active_poller.cpp
- tests/monitor.cpp
- tests/poller.cpp
Solution: Fix some compiler warnings
> Problem: Compiler warnings in tests

- .travis.yml
Solution: Exclude from analysis
> Problem: External header catch.hpp included in coverage

- .gitignore
Solution: Ignore all *build directories
> Problem: Only one build directory ignored

- zmq.hpp
Solution: Remove constructor call
> Problem: message_t ctor for iterators double initializes the message

- tests/CMakeLists.txt
- tests/message.cpp
- tests/socket.cpp
- tests/utilities.cpp
- zmq.hpp
Solution: Detect ranges with enable_if idiom
> Problem: message_t ctor for ranges too greedy

- zmq.hpp
Solution: Detect C++14 via C++17
> Problem: C++14 features not detected using MSVC

- README.md
- tests/socket.cpp
> Clarify example requirements

- zmq.hpp
Ran into a couple issues using cppzmq in our test suite.  The specific cases that gave the most trouble were Clang 5 and 3.6.    The issue was not with the compiler itself, but in the test they are linking with a slightly older version of libstdc++,  which meant in the case of using C++17,  the headers for <optional> and <string_view> were not actually available even though ZMQ_CPP17 was enabled.   
This required some additional checks to ensure that the headers were available and a means to deactivate the particular feature.  
The second on Clang 3.6 was linking with a libstdc++ from GCC 4.9 which doesn't have the is_trivially_copyable based on the previous condition.    This required adding a condition specific to libstdc++ and a version date.    This is not perfect as there are some …
> C++17 library fixes

- tests/recv_multipart.cpp
- tests/send_multipart.cpp
> Problem: No multipart tests are begin run

- zmq.hpp
- zmq_addon.hpp
Solution: Directly use optional type
> Problem: Detail namespace used in API

- tests/recv_multipart.cpp
- zmq_addon.hpp
Solution: Add recv_multipart_n function
> Problem: Missing recv multipart to fixed buffers

- zmq_addon.hpp
> Problem: Missing reference to rfc

- tests/active_poller.cpp
- tests/context.cpp
- tests/poller.cpp
Solution: fix warning, and move string literals into a std::string variable
> Problem: Warnings and duplication

- tests/poller.cpp
- zmq.hpp
> Problem: Poller size function missing

- .travis.yml
- CMakeLists.txt
- ci_build.sh
This PR for updating CMake requirements in CI.
This is a prerequisite for #466.
> Update CMake in CI

- CMakeLists.txt
- cppzmq.pc.in
> Add pkg-config file

- README.md
fix https://github.com/zeromq/cppzmq/issues/259
> docs: fix link target
